# @package suite
defaults:
  - _self_
  - task: franka_env

suite: franka_env
name: "franka_env"

# obs dims
img_size: 256
gt_depth: false

# action compute
action_type: "absolute" # absolute, delta

# task settings
action_repeat: 1
hidden_dim: 256

# train settings
num_train_steps: 100010
log_every_steps: 100
save_every_steps: 10000
history: false
history_len: 10

# eval
eval_every_steps: 200000
num_eval_episodes: 5
eval_history_len: 10

# data loading
action_after_steps: 1

# obs_keys
pixel_keys: ["pixels1", "pixels2"]
proprio_key: "proprioceptive"
feature_key: "features"

# snapshot
save_snapshot: true

task_make_fn:
  _target_: suite.baku.make
  action_repeat: ${suite.action_repeat}
  seed: ${seed}
  height: ${suite.img_size}
  width: ${suite.img_size}
  max_episode_len: ??? # to be specified later
  max_state_dim: ??? # to be specified later
  pixel_keys: ${suite.pixel_keys}
  eval: ${eval} # eval true mean use robot
  action_type: ${suite.action_type}
  use_gt_depth: ${suite.gt_depth}
