name: point-policy
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy==2.1.3
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image
  - nvidia::cudatoolkit
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - pre-commit
    - black
    - PyOpenGL-accelerate
    - protobuf==3.20.1
    - termcolor==1.1.0
    - gym==0.22.0
    - gymnasium
    - tb-nightly
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - pandas==2.2.3
    - ipdb==0.13.9
    - yapf==0.31.0
    - sklearn==0.0
    - matplotlib==3.10.0
    - opencv-python==4.11.0.86
    - sentence-transformers
    - einops==0.7.0
    - decord
    - mujoco
    - dm_control
    - diffusers==0.15.0
    - h5py
    - timm
    - blosc
    - transformers==4.45.2
    - ray==2.37.0
    - PyOpenGL==3.1.7
    - PyOpenGL-accelerate==3.1.7
    - robomimic==0.3.0
    - robosuite==1.4.1
    - huggingface_hub==0.25.2
